# Generated by Django 5.2.6 on 2025-09-24 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("enunciado", models.TextField()),
                ("respuesta_correcta", models.CharField(max_length=255)),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("Fácil", "Facil"),
                            ("Medio", "Medio"),
                            ("Difícil", "Dificil"),
                        ],
                        default="Fácil",
                        max_length=10,
                    ),
                ),
                ("puntuacion", models.IntegerField(default=10)),
                (
                    "fecha_publicacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntuacion", models.IntegerField(default=0)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta_enviada", models.CharField(max_length=255)),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "fecha_intento",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.reto"
                    ),
                ),
            ],
        ),
    ]
